apiVersion: v1
kind: Secret
metadata:
  name: pd4ml-activation-key
data:
  activation-key: RTZEMTE4RFc1TTA0OFQtNkVBTk5OOE1ETTQ0Mk5FNS0xRTBXRDRUMk1ENE4tMU9XTUFBTkVNREU4LURXWU81ME81NTQ4OC0wMURXNEQ1RU01NE8xNTQ4QTBNNVQ4VDAtWTY4RTJPVzFPNTVENE5OTllBOFkwTzU4LUFUTkE2NTI0VERENC02NTVOME8xT0E0VEUtV08yODBZRE0wTzJPTk9ENTgxQTRPT08yLThFTVk4TU9PV1Q4OC02RFRBME9NMThERUQtNTQ4MkU4MFk0MURPTzJXT0FXMDI2TldPLTYyVE1UMDhNTVc2RVdXMlRBNkVBQVdBVC1EVDJZRVQwRUQ4MjgtVzJZNEFFTjhZNAo=
type: Opaque
