/**
 * 
 */
package com.tfb.aibank.biz.component.e2ee;

/**
 * @author john
 *
 */
public enum PassRuleType {

    NO_RULE("[]"),
    LOGIN_RULE_NORMAL ("[[{ \"oldIsBlank\": { \"flag\": true } }, { \"newIsBlank\": { \"flag\": false } }, { \"oldPwdLength\": { \"min\": 6 , \"max\": 16 } }, { \"newPwdLength\": { \"flag\": false , \"min\": 6 , \"max\": 16 } }, { \"oldisNumber\": { \"flag\": false } }, { \"newisNumber\": { \"flag\": false } }, { \"oldNonSpecialSymbol\": { \"flag\": true } }, { \"newNonSpecialSymbol\": { \"flag\": false } }, { \"oldAlphanumeric\": { \"flag\": false } }, { \"newAlphanumeric\": { \"flag\": false } }, { \"checkNewOldCompare\": { \"flag\": false } }, { \"checkNewComfireCompare\": { \"flag\": false } }, { \"checkNewUidContains\": { \"flag\": false } }, { \"checkNewUuidContains\": { \"flag\": false } }] ]"),
    LOGIN_RULE_INITIAL ("[[{ \"oldIsBlank\": { \"flag\": true } }, { \"newIsBlank\": { \"flag\": false } }, { \"oldPwdLength\": { \"min\": 6 , \"max\": 6 } }, { \"newPwdLength\": { \"flag\": false , \"min\": 6 , \"max\": 16 } }, { \"oldisNumber\": { \"flag\": true } }, { \"newisNumber\": { \"flag\": false } }, { \"oldNonSpecialSymbol\": { \"flag\": true } }, { \"newNonSpecialSymbol\": { \"flag\": false } }, { \"oldAlphanumeric\": { \"flag\": false } }, { \"newAlphanumeric\": { \"flag\": false } }, { \"checkNewOldCompare\": { \"flag\": false } }, { \"checkNewComfireCompare\": { \"flag\": false } }, { \"checkNewUidContains\": { \"flag\": false } }, { \"checkNewUuidContains\": { \"flag\": false } }] ]"),
    LOGIN_RULE_4PASS ("[[{ \"oldIsBlank\": { \"flag\": true } }, { \"newIsBlank\": { \"flag\": false } }, { \"oldPwdLength\": { \"min\": 4 , \"max\": 4 } }, { \"newPwdLength\": { \"flag\": false , \"min\": 4 , \"max\": 4 } }, { \"oldisNumber\": { \"flag\": true } }, { \"newisNumber\": { \"flag\": false } }, { \"oldNonSpecialSymbol\": { \"flag\": true } }, { \"newNonSpecialSymbol\": { \"flag\": false } }, { \"oldAlphanumeric\": { \"flag\": false } }, { \"newAlphanumeric\": { \"flag\": false } }, { \"checkNewOldCompare\": { \"flag\": false } }, { \"checkNewComfireCompare\": { \"flag\": false } }, { \"checkNewUidContains\": { \"flag\": false } }, { \"checkNewUuidContains\": { \"flag\": false } }] ]"),
    // 2021.11.12 新增檢核新密碼不能包含4碼連續或重複應數字
    CHANGE_PWD_RULE  ("[[{ \"oldIsBlank\": { \"flag\": true } }, { \"newIsBlank\": { \"flag\": true } }, { \"oldPwdLength\": { \"min\": 4 , \"max\": 16 } }, { \"newPwdLength\": { \"flag\": true , \"min\": 6 , \"max\": 16 } }, { \"oldisNumber\": { \"flag\": false } }, { \"newisNumber\": { \"flag\": false } }, { \"oldNonSpecialSymbol\": { \"flag\": true } }, { \"newNonSpecialSymbol\": { \"flag\": true } }, { \"oldAlphanumeric\": { \"flag\": false } }, { \"newAlphanumeric\": { \"flag\": true } }, {\"oldIsRepeat\": {\"flag\": false,\"num\" : 4}}, {\"newIsRepeat\": {\"flag\": true,\"num\" : 4}}, {\"oldIsSeq\": {\"flag\": false,\"num\" : 4}}, {\"newIsSeq\": {\"flag\": true,\"num\" : 4}}, { \"checkNewOldCompare\": { \"flag\": true } }, { \"checkNewComfireCompare\": { \"flag\": true } }, { \"checkNewUidContains\": { \"flag\": true } }, { \"checkNewUuidContains\": { \"flag\": true } } ] ]"),
    // CHANGE_PWD_RULE ("[[{ \"oldIsBlank\": { \"flag\": true } }, { \"newIsBlank\": { \"flag\": true } }, { \"oldPwdLength\": { \"min\": 4 , \"max\": 16 } }, { \"newPwdLength\": { \"flag\": true , \"min\": 6 , \"max\": 16 } }, { \"oldisNumber\": { \"flag\": false } }, { \"newisNumber\": { \"flag\": false } }, { \"oldNonSpecialSymbol\": { \"flag\": true } }, { \"newNonSpecialSymbol\": { \"flag\": true } }, { \"oldAlphanumeric\": { \"flag\": false } }, { \"newAlphanumeric\": { \"flag\": true } }, { \"checkNewOldCompare\": { \"flag\": true } }, { \"checkNewComfireCompare\": { \"flag\": true } }, { \"checkNewUidContains\": { \"flag\": true } }, { \"checkNewUuidContains\": { \"flag\": true } } ] ]"),
    CHANGE_UUID_RULE ("[[{ \"oldIsBlank\": { \"flag\": true } }, { \"newIsBlank\": { \"flag\": true } }, { \"oldPwdLength\": {  \"min\": 4 , \"max\": 16 } }, { \"newPwdLength\": { \"flag\": false , \"min\": 4 , \"max\": 16 } }, { \"oldisNumber\": { \"flag\": false } }, { \"newisNumber\": { \"flag\": false } }, { \"oldNonSpecialSymbol\": { \"flag\": true } }, { \"newNonSpecialSymbol\": { \"flag\": true } }, { \"oldAlphanumeric\": { \"flag\": false } }, { \"newAlphanumeric\": { \"flag\": false } }, { \"checkNewOldCompare\": { \"flag\": false } }, { \"checkNewComfireCompare\": { \"flag\": false } }, { \"checkNewUidContains\": { \"flag\": false } }, { \"checkNewUuidContains\": { \"flag\": true } }] ]"),
    DB_LOGIN_RULE_NORMAL ("[[{\"length\": {\"min\": 6,\"max\": 16}}],[{ \"containEngUp\": { \"least\": 1 } }], [{ \"containNumber\": { \"least\": 1 }}]]"),
    DB_CHANGE_PWD_RULE ("[[{\"length\": {\"min\": 6,\"max\": 16}}],[{ \"containEngUp\": { \"least\": 1 } }], [{ \"containNumber\": { \"least\": 1 } }], [{\"compareOldPass\": [{ \"name\":\"oldPwd\" \"hashAlg\":[], \"encryption\":{ \"symKey\":\"%(symKey)\", \"symKeyMode\":\"%(symKeyMode)\", \"symKeyIv\":\"%(symKeyIv)\", \"prefix\":\"%(prefix)\", \"postfix\":\"%(postfix)\", },\"data\": \"%(oldPwd)\" } ] }], [{\"compareString\": [ { \"name\":\"uid\", \"data\":{ \"isEnc\":false, \"encData\":\"%(uid)\" }, \"mode\":2, \"ignoreCase\":true } ] }], [{\"compareString\": [ { \"name\":\"uuid\", \"data\":{ \"isEnc\":false, \"encData\":\"%(uuid)\" }, \"mode\":2, \"ignoreCase\":true } ] }]]"),
    // 登入後檢核是否符合規則, 密碼長度6~16、英數混雜、不可為身份證字號之一部分、不可為使用者代號之一部分, 若否則須強制變更使用者代號或密碼
    CHECK_IS_FIRST_LOGIN("[[{ \"oldIsBlank\": { \"flag\": false } }, { \"newIsBlank\": { \"flag\": false } }, { \"oldPwdLength\": { \"min\": 6 , \"max\": 16 } }, { \"newPwdLength\": { \"flag\": true , \"min\": 6 , \"max\": 16 } }, { \"oldisNumber\": { \"flag\": false } }, { \"newisNumber\": { \"flag\": false } }, { \"oldNonSpecialSymbol\": { \"flag\": true } }, { \"newNonSpecialSymbol\": { \"flag\": true } }, { \"oldAlphanumeric\": { \"flag\": true } }, { \"newAlphanumeric\": { \"flag\": true } }, { \"checkNewOldCompare\": { \"flag\": false } }, { \"checkNewComfireCompare\": { \"flag\": false } }, { \"checkNewUidContains\": { \"flag\": true } }, { \"checkNewUuidContains\": { \"flag\": true } } ] ]"),
    // 初次申請網銀檢核, 使用此rule時新舊密碼都傳入新密碼即可, 另外需要再比對全景encode之後的密碼和DB的舊密碼是否一致
    CHECK_FIRST_APPLY("[[{ \"oldIsBlank\": { \"flag\": false } }, { \"newIsBlank\": { \"flag\": true } }, { \"oldPwdLength\": { \"min\": 6 , \"max\": 16 } }, { \"newPwdLength\": { \"flag\": true , \"min\": 6 , \"max\": 16 } }, { \"oldisNumber\": { \"flag\": false } }, { \"newisNumber\": { \"flag\": false } }, { \"oldAlphanumeric\": { \"flag\": false } }, { \"newAlphanumeric\": { \"flag\": true } }, {\"newIsRepeat\": {\"flag\": true,\"num\" : 4}}, {\"oldIsSeq\": {\"flag\": false,\"num\" : 4}}, {\"newIsSeq\": {\"flag\": true,\"num\" : 4}}, { \"checkNewOldCompare\": { \"flag\": false } }, { \"checkNewComfireCompare\": { \"flag\": true } }, { \"checkNewUidContains\": { \"flag\": true } }, { \"checkNewUuidContains\": { \"flag\": true } } ] ]");
    //private String ALL_RULES = "[ { \"oldIsBlank\": { \"flag\": false } }, { \"newIsBlank\": { \"flag\": false } }, { \"oldPwdLength\": { \"flag\": false , \"min\": 6 , \"max\": 16 } }, { \"newPwdLength\": { \"flag\": false , \"min\": 6 , \"max\": 16 } }, { \"oldisNumber\": { \"flag\": false } }, { \"newisNumber\": { \"flag\": false } }, { \"oldAlphanumeric\": { \"flag\": false } }, { \"newAlphanumeric\": { \"flag\": false } }, {\"oldIsRepeat\": {\"flag\": false,\"num\" : 4}}, {\"newIsRepeat\": {\"flag\": true,\"num\" : 4}}, {\"oldIsSeq\": {\"flag\": false,\"num\" : 4}}, {\"newIsSeq\": {\"flag\": true,\"num\" : 4}}, { \"checkNewOldCompare\": { \"flag\": false } }, { \"checkNewComfireCompare\": { \"flag\": false } }, { \"checkNewUidContains\": { \"flag\": false } }, { \"checkNewUuidContains\": { \"flag\": false } } ]";
    
    String rules;
    
    PassRuleType(String rules){
        this.rules = rules;
    }
    
    public String getRules(){
        return this.rules;
    }

}
