apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-private
spec:
  selector:
    matchLabels:
      app: rabbitmq-private
  serviceName: rabbitmq-private
  replicas: 1
  template:
    metadata:
      annotations:
        io.prometheus/path: /metrics
        io.prometheus/port: "15692"
        io.prometheus/scrape: "true"
        sidecar.istio.io/inject: "false"
        oneagent.dynatrace.com/inject: "false"
      labels:
        app: rabbitmq-private
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: NotIn
      #           values:
      #           - tpebnkcldatu1w02t
      terminationGracePeriodSeconds: 10
      containers:
        - name: rabbitmq
          image: registry.groupt.fbt.com/tpebnknanot/infra/rabbitmq:4.1.3-management-alpine
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
            - containerPort: 15692
              name: prometheus
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: config-volume
              mountPath: /etc/rabbitmq/conf.d/20-load-defs.conf
              subPath: load-defs.conf
            - name: config-volume
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
            - name: config-volume
              mountPath: /etc/rabbitmq/rabbitmq-defs.json
              subPath: rabbitmq-defs-fed.json
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "secret-cookie" # Set your desired Erlang cookie value
          resources:
            limits:
              memory: 384Mi
              cpu: 500m
            requests:
              memory: 128Mi
              cpu: 50m
      volumes:
        - name: config-volume
          configMap:
            name: cm-rabbit-config
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        storageClassName: tpebnknanot-sc-lgvwit
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi

