apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-private
spec:
  clusterIP: None
  selector:
    app: rabbitmq-private
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: management
    - protocol: TCP
      port: 15692
      targetPort: 15692
      name: prometheus

